<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXEBcykI\App_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXEBcykI/App_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerXEBcykI.legacy');

    return;
}

if (!\class_exists(App_KernelProdContainer::class, false)) {
    \class_alias(\ContainerXEBcykI\App_KernelProdContainer::class, App_KernelProdContainer::class, false);
}

return new \ContainerXEBcykI\App_KernelProdContainer([
    'container.build_hash' => 'XEBcykI',
    'container.build_id' => 'd15d6c0a',
    'container.build_time' => 1725471122,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXEBcykI');
