<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container4JPhBRs\App_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container4JPhBRs/App_KernelProdContainer.php') {
    touch(__DIR__.'/Container4JPhBRs.legacy');

    return;
}

if (!\class_exists(App_KernelProdContainer::class, false)) {
    \class_alias(\Container4JPhBRs\App_KernelProdContainer::class, App_KernelProdContainer::class, false);
}

return new \Container4JPhBRs\App_KernelProdContainer([
    'container.build_hash' => '4JPhBRs',
    'container.build_id' => '14ddd1c3',
    'container.build_time' => 1728949617,
], __DIR__.\DIRECTORY_SEPARATOR.'Container4JPhBRs');
